### ISSUE TITLE
Please seed the torrent

### ISSUE THREAD

**Issue by 5H3RM** [binarygeek119/DizqueTV-Commercial-Pack#1]
If you are able to please seed the torrent. There are only 2 people seeding at the moment which will make it impossible to finish!

**Comment by binarygeek119** [comment]
my server is down right now trying to bring it back up will start to seed again once up and running

**Comment by binarygeek119** [comment]
it should be seeding now.

**Comment by Briare0s** [comment]
Thanks so much for this effort. Any chance to upload it to newsgroups?

**Comment by binarygeek119** [comment]
i can look into it in currently working on v2 so i wont tell then

**Comment by Briare0s** [comment]
Awesome, can't wait!
